[package]
name = "decoupled-llama2-rs"
version = "0.1.0"
edition = "2024"

[features]
default = ["parallel"]
parallel = []

[dependencies]
clap = "4.5.31"
memmap2 = "0.9.5"
rayon = "1.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
ctrlc = "3.4"